### ISSUE TITLE
InputDecoration not working

### ISSUE THREAD

**Issue by URSFR** [julienandco/google_places_autocomplete_text_field#1]
i cant decorate the textformfield, changes dont do anything

                         GooglePlacesAutoCompleteTextFormField(
                          textEditingController: usercontroller.placeET,
                          googleAPIKey: googleMapsApiKey,
                          // proxyURL: "https://your-proxy.com/", // only needed if you build for the web
                          debounceTime: 400, // defaults to 600 ms,
                          // countries: ["de"], // optional, by default the list is empty (no restrictions)
                          isLatLngRequired: true, // if you require the coordinates from the place details
                          getPlaceDetailWithLatLng: (prediction) {
                            // this method will return latlng with place detail
                            print("placeDetails" + prediction.lng.toString());
                          }, // this callback is called when isLatLngRequired is true
                          itmClick: (prediction) {
                            print(prediction.description);
                            print(TextSelection.fromPosition(TextPosition(offset: prediction.description!.length)));
                            usercontroller.placeET.text = prediction.description!;
                            usercontroller.placeET.selection = TextSelection.fromPosition(TextPosition(offset: prediction.description!.length));
                          },
                          style: GoogleFonts.poppins(fontSize: 16,fontWeight: FontWeight.w500),
                          decoration: InputDecoration(
                            suffixIcon: Icon(Icons.search),
                            contentPadding: EdgeInsets.all(20),
                            border: InputBorder.none,

                          ),
                        ),

**Comment by Vitaly-V** [comment]
@URSFR 
Try to use not decoration but **inputDecoration**
