### ISSUE TITLE
Flutter windows

### ISSUE THREAD

**Issue by Hopheylalal** [julienandco/google_places_autocomplete_text_field#11]
Hello. itmClick do not working. address selection does not occur

**Comment by julienandco** [comment]
Hi @Hopheylalal could you please specify?

- on what platform are you using the package?
- what flutter version are you using?
- what version of the package are you using?
- what exactly is not working? (what do you mean by `address selection`?)

Have a great week!

**Comment by julienandco** [comment]
Stale
