### ISSUE TITLE
Newlines break the input

### ISSUE THREAD

**Issue by iamdiogo** [julienandco/google_places_autocomplete_text_field#21]
On iOS, if the user inserts a newline on the input, the experience is broken (the dropdown picker appears on a different spot as it should, there is empty space on top, etc.)

Can't confirm if the same also happens on Android.

I was able to fix this issue by manually adding to the input:
```dart
inputFormatters: [
  FilteringTextInputFormatter.deny(RegExp(r'\n')),
],
```

**Comment by julienandco** [comment]
Hi @iamdiogo, thanks for submitting this issue! I was not able to reproduce the bug on iOS 17.6.1 with an iPhone 11 Pro. Could you please specify the iOS version and the device on which you encountered the bug? Also, if you could check whether the bug pops up on Android as well would be awesome!

Cheers
