### ISSUE TITLE
feat: Please Add the place api (new) using sessionToken.

### ISSUE THREAD

**Issue by varindergroove** [julienandco/google_places_autocomplete_text_field#9]
## Description
Please add to option new place api(NEW) , because using sessionToken for managing multiple hits count as single hits

## Requirements
add option to use new api or old

**Comment by julienandco** [comment]
Hi @varindergroove 

If you are working on that feature for one of your projects, would you be open to contribute via a PR? Your help to integrate this option would be very much appreciated!

Have a great week!
